# Generated by Django 5.1.3 on 2024-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_receber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receber',
        ),
    ]
